image:
  file: .gitpod.Dockerfile
ports:
  - port: 6080
    onOpen: open-preview
tasks:
  - init: pip3 install -r requirements.txt
    command: clear && python3 tdmgr.py
    name: Split terminal
  - openMode: split-right
    command: echo SplitTerminal && clear
